[package]
name = "dzta-edge-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "revocation_daemon"
path = "src/bin/revocation_daemon.rs" # Compiles into native host executable

[dependencies]
proxy-wasm = "0.2"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
# ark-bn254 = { version = "0.6.0", default-features = false }
ark-bls12-381 = { version = "0.6", default-features = false, features = ["curve"] }
ark-groth16 = { version = "0.6.0", default-features = false }
ark-serialize = { version = "0.6.0", default-features = false }
ark-std = { version = "0.6.0", default-features = false }
tonic = "0.14.6"
tokio = { version = "1.35", features = ["full"] }
fabric-sdk = { version = "0.5.8" }
prost = "0.14.4"
reqwest = { version = "0.11", features = ["json"] }
env_logger = "0.11.11"
dzta = { path = ".." }