apiVersion: apps/v1
kind: Deployment
metadata:
  name: dzta-mec-edge-ingress
  namespace: dzta-edge
  labels:
    app.kubernetes.io/layer: "4"
    app.kubernetes.io/component: "edge-enforcer"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dzta-mec-edge-ingress
  template:
    metadata:
      labels:
        app: dzta-mec-edge-ingress
    spec:
      containers:
      - name: envoy-zkp-proxy
        image: dzta-registry.internal/edge/enforcer:v1.0.0
        ports:
        - containerPort: 10000
          name: http-ingress
        - containerPort: 9901
          name: envoy-admin
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      - name: fabric-revocation-daemon
        image: dzta-registry.internal/edge/revocation-daemon:v1.0.0
        env:
        - name: FABRIC_PEER_ENDPOINT
          value: "grpcs://peer0.org1.dzta-network.com:7051"
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: dzta-edge-service
  namespace: dzta-edge
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 10000
    protocol: TCP
    name: http
  selector:
    app: dzta-mec-edge-ingress