# Workspace configuration
[workspace]
members = [
    "zkp-core-crypto",
    "tee-runner-enclave",
    "dzta-protected-prover",
    "dzta-edge-wasm",
    "toxic-waste",
    "dzta-revocation-daemon",
    "fabric-client",
    "dzta-gramine-prover",
    "shared",
    "dzta-e2e-tests",
]
resolver = "2"

[patch.crates-io]