use ark_bls12_381::{Bls12_381, Fr};
use ark_ff::PrimeField;
use ark_groth16::{Groth16, ProvingKey};
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use ark_snark::SNARK;
use num_bigint::BigUint;
use num_traits::Num;
use rand_chacha::{rand_core::SeedableRng, ChaCha20Rng};
use serde::Deserialize;
use std::io::{self, Read};

use zkp_core_crypto::RoleVerificationCircuit;

/// JSON Input struct expected via stdin
#[derive(Deserialize)]
struct ProverInputs {
    user_clearance_level: u8,
    user_role_scalar: String,
    secret_nullifier: Vec<u8>,
    required_clearance_level: u8,
    public_commitment: Vec<u8>,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // 1. Ingest JSON payload streamed via stdin
    let mut buffer = String::new();
    io::stdin().read_to_string(&mut buffer)?;

    let inputs: ProverInputs = serde_json::from_str(&buffer)
        .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?;

    // 2. Map raw input fields into BLS12-381 Scalar Field elements (Fr)
    let user_clearance_fr = Fr::from(inputs.user_clearance_level);

    let role_biguint = BigUint::from_str_radix(&inputs.user_role_scalar, 10)
        .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?;
    let role_scalar_fr = Fr::from_le_bytes_mod_order(&role_biguint.to_bytes_le());

    let nullifier_fr = Fr::from_le_bytes_mod_order(&inputs.secret_nullifier);
    let req_clearance_fr = Fr::from(inputs.required_clearance_level);
    let commitment_fr = Fr::from_le_bytes_mod_order(&inputs.public_commitment);

    // 3. Load pre-baked Proving Key generated by setup binary
    let pk_bytes = include_bytes!("../assets/proving_key.bin");
    let proving_key = ProvingKey::<Bls12_381>::deserialize_compressed(&pk_bytes[..])
        .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?;

    // 4. Seed isolated ChaCha20 RNG from nullifier bytes
    let seed: [u8; 32] = inputs
        .secret_nullifier
        .as_slice()
        .try_into()
        .map_err(|_| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                "secret_nullifier must be exactly 32 bytes for RNG initialization",
            )
        })?;
    let mut rng = ChaCha20Rng::from_seed(seed);

    // 5. Instantiate circuit with populated scalar field values
    let circuit = RoleVerificationCircuit {
        user_clearance_level: Some(user_clearance_fr),
        user_role_scalar: Some(role_scalar_fr),
        secret_nullifier: Some(nullifier_fr),
        required_clearance_level: Some(req_clearance_fr),
        public_commitment: Some(commitment_fr),
    };

    // 6. Generate Groth16 zero-knowledge proof
    let proof = Groth16::<Bls12_381>::create_random_proof_with_reduction(
        circuit,
        &proving_key,
        &mut rng,
    )
    .map_err(|e| {
        io::Error::new(
            io::ErrorKind::Other,
            format!("ZKP Generation Failed: {:?}", e),
        )
    })?;

    // 7. Serialize proof output to hex over stdout
    let mut proof_bytes = Vec::new();
    proof
        .serialize_compressed(&mut proof_bytes)
        .map_err(|e| io::Error::new(io::ErrorKind::Other, e))?;

    println!("{}", hex::encode(proof_bytes));
    Ok(())
}