use ark_bls12_381::{Bls12_381, Fr};
use ark_groth16::{Groth16, PreparedVerifyingKey, Proof, VerifyingKey};
use ark_serialize::CanonicalDeserialize;
use base64::engine::general_purpose::STANDARD as BASE64;
use base64::Engine;
use proxy_wasm::traits::*;
use proxy_wasm::types::*;
use std::sync::OnceLock;

// Direct C call into proxy-wasm ABI to register child root contexts
extern "C" {
    fn proxy_on_context_create(context_id: u32, parent_context_id: u32);
}

// Embedded Verification Key generated by the setup binary
const VK_BYTES: &[u8] = include_bytes!("../keys/edge_verification_key.bin");

// Global static for lazy initialization
static PVK: OnceLock<Option<PreparedVerifyingKey<Bls12_381>>> = OnceLock::new();

fn get_pvk() -> Option<&'static PreparedVerifyingKey<Bls12_381>> {
    PVK.get_or_init(|| {
        log::info!("Layer 4 Wasm: Lazily preparing Groth16 Verification Key...");
        match VerifyingKey::<Bls12_381>::deserialize_compressed(VK_BYTES) {
            Ok(vk) => {
                let prepared = ark_groth16::prepare_verifying_key(&vk);
                log::info!("Layer 4 Wasm: Groth16 Verification Key prepared successfully.");
                Some(prepared)
            }
            Err(e) => {
                log::error!("Layer 4 Wasm: Failed to deserialize VK: {:?}", e);
                None
            }
        }
    })
    .as_ref()
}

proxy_wasm::main!({
    proxy_wasm::set_log_level(LogLevel::Info);
    proxy_wasm::set_root_context(|context_id| -> Box<dyn RootContext> {
        Box::new(ZkpAuthzRoot { context_id })
    });
});

struct ZkpAuthzRoot {
    context_id: u32,
}

impl Context for ZkpAuthzRoot {}

impl RootContext for ZkpAuthzRoot {
    fn on_vm_start(&mut self, _vm_configuration_size: usize) -> bool {
        log::info!("Layer 4 Wasm: Root Context {} started.", self.context_id);
        true
    }

    fn on_configure(&mut self, _plugin_configuration_size: usize) -> bool {
        log::info!("Layer 4 Wasm: Root Context {} configured.", self.context_id);
        true
    }

    fn create_http_context(&self, context_id: u32) -> Option<Box<dyn HttpContext>> {
        // If VM Root Context (1) is asked to create Plugin Context (2),
        // force SDK to insert context_id into CONTEXTS map as ContextType::Root
        if self.context_id == 1 {
            log::info!(
                "Layer 4 Wasm: VM Root 1 bridging Plugin Root Context {} to SDK.",
                context_id
            );
            unsafe {
                proxy_on_context_create(context_id, 0);
            }
            return None;
        }

        // Plugin Root Context (2+) creates actual HTTP Request Stream Contexts (3+)
        log::info!(
            "Layer 4 Wasm: Plugin Root {} creating HTTP Context {}.",
            self.context_id,
            context_id
        );
        Some(Box::new(ZkpAuthzHttp))
    }
}

struct ZkpAuthzHttp;

impl Context for ZkpAuthzHttp {}

impl HttpContext for ZkpAuthzHttp {
    fn on_http_request_headers(&mut self, _num_headers: usize, _end_of_stream: bool) -> Action {
        let pvk = match get_pvk() {
            Some(p) => p,
            None => {
                log::error!("Wasm context error: Failed to load Groth16 Verifying Key");
                self.send_http_response(500, vec![], Some(b"Internal Server Error: Missing VK\n"));
                return Action::Pause;
            }
        };

        let proof_header = self.get_http_request_header("x-dzta-proof");
        let inputs_header = self.get_http_request_header("x-dzta-public-inputs");
        let rev_status_header = self.get_http_request_header("x-dzta-revocation-id");

        if proof_header.is_none() || inputs_header.is_none() {
            log::warn!("Access Denied: Missing dZTA proof headers");
            self.send_http_response(401, vec![], Some(b"Unauthorized: Missing dZTA ZKP Headers\n"));
            return Action::Pause;
        }

        let proof_raw = proof_header.unwrap();
        let inputs_raw = inputs_header.unwrap();

        match self.verify_zkp(pvk, &proof_raw, &inputs_raw) {
            Ok(true) => log::info!("Groth16 ZK Proof successfully validated."),
            Ok(false) => {
                log::warn!("Access Denied: Invalid Groth16 ZK Proof");
                self.send_http_response(403, vec![], Some(b"Forbidden: Invalid ZK Proof\n"));
                return Action::Pause;
            }
            Err(e) => {
                log::error!("ZKP Verification Error: {}", e);
                self.send_http_response(400, vec![], Some(b"Bad Request: Malformed ZKP Data\n"));
                return Action::Pause;
            }
        }

        if let Some(rev_id) = rev_status_header {
            if self.is_revoked(&rev_id) {
                log::warn!("Access Denied: Credential ID {} has been revoked", rev_id);
                self.send_http_response(403, vec![], Some(b"Forbidden: Credential Revoked\n"));
                return Action::Pause;
            }
        }

        Action::Continue
    }
}

impl ZkpAuthzHttp {
    fn verify_zkp(
        &self,
        pvk: &PreparedVerifyingKey<Bls12_381>,
        proof_b64: &str,
        inputs_b64: &str,
    ) -> Result<bool, String> {
        let proof_bytes = BASE64
            .decode(proof_b64)
            .map_err(|e| format!("Base64 proof decode error: {}", e))?;
        let inputs_bytes = BASE64
            .decode(inputs_b64)
            .map_err(|e| format!("Base64 public inputs decode error: {}", e))?;

        let proof = Proof::<Bls12_381>::deserialize_compressed(&proof_bytes[..])
            .map_err(|e| format!("Proof deserialization error: {:?}", e))?;

        let public_inputs = Vec::<Fr>::deserialize_compressed(&inputs_bytes[..])
            .map_err(|e| format!("Inputs deserialization error: {:?}", e))?;

        Groth16::<Bls12_381>::verify_proof(pvk, &proof, &public_inputs)
            .map_err(|e| format!("Verification algorithm error: {:?}", e))
    }

    fn is_revoked(&self, revocation_id: &str) -> bool {
        let path = format!("revoked.{}", revocation_id);
        if let Some(val) = self.get_property(vec!["runtime", &path]) {
            return val == b"true";
        }
        false
    }
}


fn verify_zkp(
    &self,
    pvk: &PreparedVerifyingKey<Bls12_381>,
    proof_b64: &str,
    inputs_b64: &str,
) -> Result<bool, String> {
    log::info!("Attempting ZKP verification...");
    
    // Decode proof
    let proof_bytes = match BASE64.decode(proof_b64) {
        Ok(b) => {
            log::info!("✓ Proof base64 decoded successfully ({} bytes)", b.len());
            b
        }
        Err(e) => {
            log::error!("✗ Proof base64 decode failed: {}", e);
            return Err(format!("Base64 proof decode error: {}", e));
        }
    };

    // Decode inputs
    let inputs_bytes = match BASE64.decode(inputs_b64) {
        Ok(b) => {
            log::info!("✓ Inputs base64 decoded successfully ({} bytes)", b.len());
            b
        }
        Err(e) => {
            log::error!("✗ Inputs base64 decode failed: {}", e);
            return Err(format!("Base64 public inputs decode error: {}", e));
        }
    };

    // Deserialize proof
    let proof = match Proof::<Bls12_381>::deserialize_compressed(&proof_bytes[..]) {
        Ok(p) => {
            log::info!("✓ Proof deserialized successfully");
            p
        }
        Err(e) => {
            log::error!("✗ Proof deserialization failed: {:?}", e);
            return Err(format!("Proof deserialization error: {:?}", e));
        }
    };

    // Deserialize inputs
    let public_inputs = match Vec::<Fr>::deserialize_compressed(&inputs_bytes[..]) {
        Ok(pi) => {
            log::info!("✓ Public inputs deserialized successfully ({} inputs)", pi.len());
            pi
        }
        Err(e) => {
            log::error!("✗ Public inputs deserialization failed: {:?}", e);
            return Err(format!("Inputs deserialization error: {:?}", e));
        }
    };

    // Verify
    log::info!("Executing Groth16 verification algorithm...");
    match Groth16::<Bls12_381>::verify_proof(pvk, &proof, &public_inputs) {
        Ok(valid) => {
            log::info!("✓ Verification result: {}", valid);
            Ok(valid)
        }
        Err(e) => {
            log::error!("✗ Verification algorithm failed: {:?}", e);
            Err(format!("Verification algorithm error: {:?}", e))
        }
    }
}


/// Pushes the revoked ID to Envoy's local runtime admin memory endpoint with retries.
async fn sync_to_envoy_memory(&self, credential_id: &str) {
    let url = format!(
        "{}/runtime_modify?revoked.{}=true",
        self.envoy_admin_url.trim_end_matches('/'),
        credential_id
    );

    let client = reqwest::Client::new();
    let mut retries = 5;
    let mut delay = Duration::from_millis(500);

    while retries > 0 {
        match client.post(&url).timeout(Duration::from_secs(5)).send().await {
            Ok(res) if res.status().is_success() => {
                info!(
                    "[Layer 4 Daemon] Successfully injected revocation [{}] into Envoy Wasm runtime cache.",
                    credential_id
                );
                return;
            }
            Ok(res) => {
                warn!(
                    "[Layer 4 Daemon] Envoy runtime update returned HTTP {}. Retrying in {}ms...",
                    res.status(),
                    delay.as_millis()
                );
            }
            Err(e) => {
                warn!(
                    "[Layer 4 Daemon] Envoy Admin API not ready ({:?}). Retrying in {}ms... ({} attempts left)",
                    e,
                    delay.as_millis(),
                    retries - 1
                );
            }
        }

        tokio::time::sleep(delay).await;
        delay = std::cmp::min(delay * 2, Duration::from_secs(5));
        retries -= 1;
    }

    error!(
        "[Layer 4 Daemon] Permanent failure injecting revocation [{}] into Envoy.",
        credential_id
    );
}

# Syntax = docker/dockerfile:1
# ==============================================================================
# Stage 1: Pure Rust WASM Builder
# ==============================================================================
FROM rustlang/rust:nightly-slim AS builder

# Add WASM target
RUN rustup target add wasm32-wasip1

WORKDIR /usr/src/app

# 1. Copy ONLY the WASM crate source
COPY dzta-edge-wasm ./dzta-edge-wasm

# 2. Dynamically overwrite Cargo.toml to list ONLY dzta-edge-wasm as workspace member
RUN printf '[workspace]\nmembers = ["dzta-edge-wasm"]\nresolver = "2"\n' > Cargo.toml

# 3. Compile WASM binary (NO wasm-opt to avoid ABI corruption)
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/src/app/target \
    cargo build --package dzta-edge-wasm --target wasm32-wasip1 --release --lib && \
    mkdir -p /out && \
    cp target/wasm32-wasip1/release/dzta_edge_wasm.wasm /out/dzta_edge_wasm.wasm

# ==============================================================================
# Stage 2: Envoy Runtime
# ==============================================================================
FROM envoyproxy/envoy:v1.30.1

WORKDIR /etc/envoy

COPY --from=builder /out/dzta_edge_wasm.wasm ./dzta_edge_wasm.wasm
COPY dzta-edge-wasm/envoy.yaml ./envoy.yaml
COPY dzta-edge-wasm/keys ./keys

EXPOSE 10000 9901
CMD ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]